// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2450.Test2018;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainSubsystemLeftMotor;
    public static SpeedController driveTrainSubsystemRightMotor;
    public static RobotDrive driveTrainSubsystemRobotDrive2;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    public static boolean chuteFront = false;
    
    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainSubsystemLeftMotor = new Spark(0);
        LiveWindow.addActuator("DriveTrainSubsystem", "LeftMotor", (Spark) driveTrainSubsystemLeftMotor);
        
        driveTrainSubsystemRightMotor = new Spark(1);
        LiveWindow.addActuator("DriveTrainSubsystem", "RightMotor", (Spark) driveTrainSubsystemRightMotor);
        
        driveTrainSubsystemRobotDrive2 = new RobotDrive(driveTrainSubsystemLeftMotor, driveTrainSubsystemRightMotor);
        
        driveTrainSubsystemRobotDrive2.setSafetyEnabled(true);
        driveTrainSubsystemRobotDrive2.setExpiration(0.1);
        driveTrainSubsystemRobotDrive2.setSensitivity(0.5);
        driveTrainSubsystemRobotDrive2.setMaxOutput(1.0);
        driveTrainSubsystemRobotDrive2.setInvertedMotor(RobotDrive.MotorType.kRearLeft, true);
        driveTrainSubsystemRobotDrive2.setInvertedMotor(RobotDrive.MotorType.kRearRight, true);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
