// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2450.TimmyTurner.commands;
import edu.wpi.first.wpilibj.Preferences;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;
import edu.wpi.first.wpilibj.interfaces.Gyro;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc2450.TimmyTurner.Robot;
import org.usfirst.frc2450.TimmyTurner.RobotMap;
import org.usfirst.frc2450.TimmyTurner.subsystems.ADXRS453Gyro;

/**
 *
 */
public class TurnRight extends Command {
	Preferences prefs; 
	double targetangle;
	double targetdivident;
	double targetspeed;
	double P = 0.4;
	double I = 0.45;
	double D = 0;
	double integral, previous_error, setpoint = 0;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
	double rcw;
	double error;
	double derivative;
	double proportional;
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public TurnRight(double targetangle) {
    	SmartDashboard.putString("Right Value of RCW", "rcw: " + rcw);
       	SmartDashboard.putString("Right Integral", "Integral: " + integral);
    	
    	

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    public void setSetpoint(int setpoint)
    {
    	this.setpoint = setpoint;
    }
    
    public void PID()
    {
    	//error = setpoint - RobotMap.gyroSPI.getAngle();
    	error = (targetangle - RobotMap.gyroSPI.getAngle())/90;
    	proportional = P * error;
    	this.integral += (error*.02);
    	derivative = (error - this.previous_error) / .02;
    	this.rcw = proportional + I*this.integral + D*derivative;
    }
    protected void initialize() {
    	RobotMap.gyroSPI.reset();
    	prefs = Preferences.getInstance();
    	targetangle = prefs.getDouble("targetangle", 1.0);
    	targetdivident = prefs.getDouble("targetdivident", 250.0);
    	targetspeed = prefs.getDouble("targetspeed", 0.2);
    	proportional = 0;
    	integral = 0;
    	derivative = 0;
    }
    
    private double speed()
    {
    	return targetspeed + (targetangle - RobotMap.gyroSPI.getAngle())/targetdivident;
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
//    	double turnfraction = 1 - ((90 - RobotMap.driveTrainSubsystemGyro.getAngle())/ 90);
//    	org.usfirst.frc2450.TimmyTurner.RobotMap.driveTrainSubsystemLeftMotor.set(0.57 * turnfraction);
//    	org.usfirst.frc2450.TimmyTurner.RobotMap.driveTrainSubsystemRightMotor.set(0.5 * turnfraction);
    	PID();
//    	org.usfirst.frc2450.TimmyTurner.RobotMap.driveTrainSubsystemRobotDrive2.arcadeDrive(0, rcw);
    	org.usfirst.frc2450.TimmyTurner.RobotMap.driveTrainSubsystemRobotDrive2.tankDrive(rcw, -rcw, false);
    	SmartDashboard.putString("Right Value of RCW", "rcw: " + rcw);
       	SmartDashboard.putString("Right Integral", "Integral: " + integral);
    	
//    	org.usfirst.frc2450.TimmyTurner.RobotMap.driveTrainSubsystemLeftMotor.set(speed());
//    	org.usfirst.frc2450.TimmyTurner.RobotMap.driveTrainSubsystemRightMotor.set(speed());
//    	
    	
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return (RobotMap.gyroSPI.getAngle() >= targetangle);
    }

    // Called once after isFinished returns true
    protected void end() {
    	org.usfirst.frc2450.TimmyTurner.RobotMap.driveTrainSubsystemRobotDrive2.stopMotor();
    	RobotMap.driveTrainSubsystemRightEncoder.reset();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
